server:
  port: 7070

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: myuser
      password: 123456
      database: myworld

my:
  elasticsearch:
    host: localhost
    port: 9200
    scheme: http

